"""Bundled card data for offline/fallback use.

Contains all commonly-used staple cards, hand traps, extra deck monsters,
and popular archetype cores so the deck builder works without an internet
connection. Full database (~13,000+ cards) is downloaded from YGOPRODeck
on first run.

Format: each entry is a dict matching the YGOPRODeck API schema.
"""


def _c(id, name, typ, desc, race, arch, atk, dfn, lvl, rnk, lnk, scl, attr, ban=0):
    """Compact card constructor. ban: 0=Unlimited 1=Semi 2=Limited 3=Banned"""
    ban_map = {0: "Unlimited", 1: "Semi-Limited", 2: "Limited", 3: "Banned"}
    d = {"id": id, "name": name, "type": typ, "desc": desc, "race": race}
    if arch:
        d["archetype"] = arch
    if atk is not None:
        d["atk"] = atk
    if dfn is not None:
        d["def"] = dfn
    if lvl:
        d["level"] = lvl
    if rnk:
        d["rank"] = rnk
    if lnk:
        d["linkval"] = lnk
    if scl is not None:
        d["scale"] = scl
    if attr:
        d["attribute"] = attr
    if ban:
        d["banlist_info"] = {"ban_tcg": ban_map[ban]}
    else:
        d["banlist_info"] = {}
    return d


# fmt: off
BUNDLED_CARDS = [
    # ===== HAND TRAPS =====
    _c(14558127, "Ash Blossom & Joyous Spring", "Tuner Monster",
       "When a card or effect is activated that includes any of these effects (Quick Effect): You can discard this card; negate that effect. Add a card from the Deck to the hand. Special Summon from the Deck. Send a card from the Deck to the GY.",
       "Zombie", None, 0, 1800, 3, 0, 0, None, "FIRE"),
    _c(59438930, "Ghost Ogre & Snow Rabbit", "Tuner Monster",
       "When a monster on the field activates its effect, or when a Spell/Trap that is already face-up on the field activates its effect (Quick Effect): You can send this card from your hand or field to the GY; destroy that card on the field.",
       "Psychic", None, 0, 1800, 3, 0, 0, None, "LIGHT"),
    _c(73642296, "Ghost Belle & Haunted Mansion", "Tuner Monster",
       "When a card or effect is activated that includes any of these effects (Quick Effect): You can discard this card; negate that effect. Add a card from the GY to the hand, Deck, or Extra Deck. Special Summon a Monster Card from the GY. Banish a card from the GY.",
       "Zombie", None, 0, 1800, 3, 0, 0, None, "EARTH"),
    _c(52038441, "Ghost Mourner & Moonlit Chill", "Tuner Monster",
       "If your opponent Special Summons a monster(s) face-up (except during the Damage Step): You can discard this card; negate the effects of 1 of those monsters.",
       "Zombie", None, 0, 1800, 3, 0, 0, None, "WIND"),
    _c(97268402, "Effect Veiler", "Tuner Monster",
       "During your opponent's Main Phase (Quick Effect): You can send this card from your hand to the GY, then target 1 Effect Monster your opponent controls; negate the effects of that face-up monster your opponent controls, until the end of this turn.",
       "Spellcaster", None, 0, 0, 1, 0, 0, None, "LIGHT"),
    _c(27204311, "Nibiru, the Primal Being", "Effect Monster",
       "During the Main Phase, if your opponent Normal or Special Summoned 5 or more monsters this turn (Quick Effect): You can Tribute as many face-up monsters on the field as possible, and if you do, Special Summon this card from your hand, then Special Summon 1 \"Primal Being Token\".",
       "Rock", None, 3000, 600, 11, 0, 0, None, "LIGHT"),
    _c(10045474, "Infinite Impermanence", "Trap Card",
       "Target 1 face-up monster your opponent controls; negate its effects until the end of this turn. If you control no cards, you can activate this card from your hand.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(32807846, "Maxx \"C\"", "Effect Monster",
       "During either player's turn: You can send this card from your hand to the GY; this turn, each time your opponent Special Summons a monster(s), immediately draw 1 card.",
       "Insect", None, 500, 200, 2, 0, 0, None, "EARTH", 2),
    _c(94145021, "D.D. Crow", "Effect Monster",
       "During either player's turn: You can discard this card to the GY, then target 1 card in your opponent's GY; banish that target.",
       "Winged Beast", None, 100, 100, 1, 0, 0, None, "DARK"),
    _c(94145683, "Droll & Lock Bird", "Effect Monster",
       "If your opponent adds a card(s) from their Deck to their hand, except during the Draw Phase (Quick Effect): You can send this card from your hand to the GY; for the rest of this turn, neither player can add cards from their Deck to their hand.",
       "Spellcaster", None, 0, 0, 1, 0, 0, None, "WIND"),
    _c(34267821, "Artifact Lancea", "Effect Monster",
       "During your opponent's turn (Quick Effect): You can Tribute this card from your hand or face-up field; neither player can banish cards for the rest of this turn.",
       "Fairy", None, 1700, 2300, 5, 0, 0, None, "LIGHT"),
    _c(38814750, "PSY-Framegear Gamma", "Tuner Monster",
       "When a monster effect is activated while you control no monsters (Quick Effect): You can Special Summon both this card from your hand and 1 \"PSY-Frame Driver\" from your hand, Deck, or GY, and if you do, negate that activation, and if you do that, destroy that monster.",
       "Psychic", None, 1000, 0, 2, 0, 0, None, "LIGHT"),
    _c(34950327, "PSY-Frame Driver", "Normal Monster",
       "A extrasensory soldier that is the heart of the \"PSY-Frame\" deck.",
       "Psychic", None, 2500, 0, 6, 0, 0, None, "LIGHT"),
    _c(91800273, "Dimension Shifter", "Effect Monster",
       "If you have no cards in your GY (Quick Effect): You can send this card from your hand to the GY; until the end of the next turn, any card sent to the GY is banished instead.",
       "Spellcaster", None, 1200, 2200, 6, 0, 0, None, "DARK"),
    _c(60643553, "Skull Meister", "Effect Monster",
       "When a card effect is activated in your opponent's GY (Quick Effect): You can send this card from your hand to the GY; negate that effect.",
       "Fiend", None, 1700, 400, 4, 0, 0, None, "DARK"),
    _c(65203212, "Token Collector", "Effect Monster",
       "If a Token(s) is Special Summoned (Quick Effect): You can Special Summon this card from your hand or GY, and if you do, destroy all Tokens on the field.",
       "Fiend", None, 0, 2000, 4, 0, 0, None, "EARTH"),
    _c(23434538, "Contact \"C\"", "Effect Monster",
       "When your opponent Special Summons a monster from the Extra Deck: You can Special Summon this card from your hand to your opponent's field in Defense Position.",
       "Insect", None, 1500, 2200, 6, 0, 0, None, "EARTH"),
    _c(21011044, "Mulcharmy Fuwalos", "Effect Monster",
       "If your opponent Special Summons a monster(s) from the Deck (except during the Damage Step): You can reveal this card in your hand; for the rest of this turn, each time your opponent Special Summons a monster(s) from the Deck, immediately draw 1 card.",
       "Beast", None, 100, 600, 1, 0, 0, None, "LIGHT"),
    _c(26674724, "Mulcharmy Purulia", "Effect Monster",
       "If your opponent adds a card(s) from the Deck to the hand, except by drawing (Quick Effect): You can reveal this card in your hand; draw 1 card each time your opponent adds card(s) from Deck to hand for the rest of this turn.",
       "Beast", None, 100, 600, 1, 0, 0, None, "EARTH"),
    _c(92714517, "Mulcharmy Nyalus", "Effect Monster",
       "If your opponent sends a card(s) from the Deck to the GY (except during the Damage Step): You can reveal this card; draw 1 card each time your opponent sends card(s) from Deck to GY for the rest of this turn.",
       "Beast", None, 100, 600, 1, 0, 0, None, "WATER"),

    # ===== STAPLE SPELLS =====
    _c(24224830, "Called by the Grave", "Spell Card",
       "Target 1 monster in your opponent's GY; banish it, and if you do, until the end of the next turn, its effects are negated, as well as the activated effects and effects on the field of monsters with the same original name.",
       "Quick-Play", None, None, None, 0, 0, 0, None, None, 2),
    _c(65681983, "Crossout Designator", "Spell Card",
       "Declare 1 card name; until the end of this turn, that card, and its effects, are negated, and if you do, banish 1 card with that name from your Deck.",
       "Quick-Play", None, None, None, 0, 0, 0, None, None),
    _c(29616929, "Triple Tactics Talent", "Spell Card",
       "If your opponent has activated a monster effect during this Main Phase: Activate 1 of these effects; Draw 2 cards. Take control of 1 monster your opponent controls until the End Phase. Look at your opponent's hand, and choose 1 card from it and shuffle it into the Deck.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(12580477, "Forbidden Droplet", "Spell Card",
       "Send any number of other cards from your hand and/or field to the GY; choose that many Effect Monsters your opponent controls, and until the end of this turn, their ATK is halved, also their effects are negated. Your opponent cannot activate cards or effects in response.",
       "Quick-Play", None, None, None, 0, 0, 0, None, None),
    _c(14532163, "Forbidden Chalice", "Spell Card",
       "Target 1 face-up monster on the field; until the end of this turn, that target gains 400 ATK, but its effects are negated.",
       "Quick-Play", None, None, None, 0, 0, 0, None, None),
    _c(18144506, "Harpie's Feather Duster", "Spell Card",
       "Destroy all Spell and Trap Cards your opponent controls.",
       "Normal", None, None, None, 0, 0, 0, None, None, 2),
    _c(12580477, "Lightning Storm", "Spell Card",
       "If you control no face-up cards: Activate 1 of these effects; Destroy all Attack Position monsters your opponent controls. Destroy all Spells and Traps your opponent controls.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(26302522, "Raigeki", "Spell Card",
       "Destroy all monsters your opponent controls.",
       "Normal", None, None, None, 0, 0, 0, None, None, 2),
    _c(53129443, "Dark Hole", "Spell Card",
       "Destroy all monsters on the field.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(5318639, "Mystical Space Typhoon", "Spell Card",
       "Target 1 Spell/Trap on the field; destroy that target.",
       "Quick-Play", None, None, None, 0, 0, 0, None, None),
    _c(43898403, "Twin Twisters", "Spell Card",
       "Discard 1 card, then target up to 2 Spell/Trap Cards on the field; destroy them.",
       "Quick-Play", None, None, None, 0, 0, 0, None, None),
    _c(8267140, "Cosmic Cyclone", "Spell Card",
       "Pay 1000 LP, then target 1 Spell/Trap on the field; banish it.",
       "Quick-Play", None, None, None, 0, 0, 0, None, None),
    _c(35261759, "Pot of Desires", "Spell Card",
       "Banish 10 cards from the top of your Deck, face-down; draw 2 cards.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(49238328, "Pot of Extravagance", "Spell Card",
       "At the start of your Main Phase 1: Banish 3 or 6 random face-down cards from your Extra Deck; draw 1 card for every 3 cards banished.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(84211599, "Pot of Prosperity", "Spell Card",
       "At the start of your Main Phase 1: Banish 3 or 6 cards of your choice from your Extra Deck, face-down; for each card banished, excavate 1 card from the top of your Deck, add 1 of them to your hand, place the rest on the bottom of your Deck in any order.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(98645731, "Pot of Duality", "Spell Card",
       "Excavate the top 3 cards of your Deck, add 1 of them to your hand, also shuffle the rest back. You cannot Special Summon during the turn you activate this card.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(1753560, "Upstart Goblin", "Spell Card",
       "Draw 1 card, then your opponent gains 1000 LP.",
       "Normal", None, None, None, 0, 0, 0, None, None, 2),
    _c(81439173, "Pot of Avarice", "Spell Card",
       "Target 5 monsters in your GY; shuffle all 5 into the Deck, then draw 2 cards.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(59750328, "Card of Demise", "Spell Card",
       "Draw until you have 3 cards in your hand, also for the rest of this turn after this card resolves, your opponent takes no damage. During the End Phase, send your entire hand to the GY. You cannot Special Summon during the turn you activate this card.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(32807846, "Terraforming", "Spell Card",
       "Add 1 Field Spell from your Deck to your hand.",
       "Normal", None, None, None, 0, 0, 0, None, None, 2),
    _c(81439174, "Foolish Burial", "Spell Card",
       "Send 1 monster from your Deck to the GY.",
       "Normal", None, None, None, 0, 0, 0, None, None, 2),
    _c(35726888, "Foolish Burial Goods", "Spell Card",
       "Send 1 Spell/Trap from your Deck to the GY.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(2295440, "One for One", "Spell Card",
       "Send 1 monster from your hand to the GY; Special Summon 1 Level 1 monster from your hand or Deck.",
       "Normal", None, None, None, 0, 0, 0, None, None, 2),
    _c(32807851, "Reinforcement of the Army", "Spell Card",
       "Add 1 Level 4 or lower Warrior monster from your Deck to your hand.",
       "Normal", None, None, None, 0, 0, 0, None, None, 2),
    _c(45906428, "Emergency Teleport", "Spell Card",
       "Special Summon 1 Level 3 or lower Psychic monster from your hand or Deck, but banish it during the End Phase of this turn.",
       "Quick-Play", None, None, None, 0, 0, 0, None, None),
    _c(83764718, "Monster Reborn", "Spell Card",
       "Target 1 monster in either GY; Special Summon it.",
       "Normal", None, None, None, 0, 0, 0, None, None, 2),
    _c(48130397, "Super Polymerization", "Spell Card",
       "Discard 1 card; Fusion Summon 1 Fusion Monster from your Extra Deck, using monsters from either field as Fusion Material. Neither player can activate cards or effects in response to this card's activation.",
       "Quick-Play", None, None, None, 0, 0, 0, None, None),
    _c(4031928, "Book of Moon", "Spell Card",
       "Target 1 face-up monster on the field; change that target to face-down Defense Position.",
       "Quick-Play", None, None, None, 0, 0, 0, None, None),
    _c(31036355, "Change of Heart", "Spell Card",
       "Target 1 monster your opponent controls; take control of it until the End Phase.",
       "Normal", None, None, None, 0, 0, 0, None, None, 2),
    _c(55375919, "Small World", "Spell Card",
       "Reveal 1 monster in your hand, then reveal 1 monster from your Deck that has exactly 1 of Type, Attribute, Level, ATK, or DEF in common with the revealed monster; banish the revealed monster from your hand face-down, and add to your hand 1 monster from your Deck that has exactly 1 shared property with the monster revealed from the Deck. You can only activate 1 \"Small World\" per turn.",
       "Normal", None, None, None, 0, 0, 0, None, None),

    # ===== STAPLE TRAPS =====
    _c(41420027, "Solemn Judgment", "Trap Card",
       "When a monster(s) would be Summoned, OR when a Spell/Trap Card is activated: Pay half your LP; negate the Summon or activation, and if you do, destroy that card.",
       "Counter", None, None, None, 0, 0, 0, None, None),
    _c(12580477, "Solemn Warning", "Trap Card",
       "When a monster(s) would be Summoned, or when a Spell/Trap Card or monster effect is activated that includes an effect that Special Summons a monster(s): Pay 2000 LP; negate the Summon or activation, and if you do, destroy that card.",
       "Counter", None, None, None, 0, 0, 0, None, None),
    _c(40605147, "Solemn Strike", "Trap Card",
       "When a monster(s) would be Special Summoned, or a monster effect is activated: Pay 1500 LP; negate the Summon or activation, and if you do, destroy that card.",
       "Counter", None, None, None, 0, 0, 0, None, None),
    _c(53582587, "Torrential Tribute", "Trap Card",
       "When a monster(s) is Summoned: Destroy all monsters on the field.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(29401950, "Bottomless Trap Hole", "Trap Card",
       "When your opponent Summons a monster(s) with 1500 or more ATK: Destroy that monster(s) and banish it.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(94192409, "Compulsory Evacuation Device", "Trap Card",
       "Target 1 monster on the field; return that target to the hand.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(15693423, "Evenly Matched", "Trap Card",
       "At the end of the Battle Phase, if your opponent controls more cards than you do: You can make your opponent banish face-down cards they control so they control the same number of cards as you do. If you control no cards, you can activate this card from your hand.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(26905245, "Ice Dragon's Prison", "Trap Card",
       "Target 1 monster in your opponent's GY; Special Summon it to your field, then banish 1 monster on the field with the same Type as that monster.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(99188141, "Trap Trick", "Trap Card",
       "Banish 1 Normal Trap from your Deck, except \"Trap Trick\"; Set 1 card with the same name from your Deck to your Spell & Trap Zone. You can activate the Set card this turn.",
       "Normal", None, None, None, 0, 0, 0, None, None),

    # ===== FLOODGATES =====
    _c(82732705, "Skill Drain", "Trap Card",
       "Activate by paying 1000 LP. The effects of all face-up monsters on the field are negated.",
       "Continuous", None, None, None, 0, 0, 0, None, None),
    _c(90846359, "Rivalry of Warlords", "Trap Card",
       "Each player can only control 1 Type of monster. Send all other face-up monsters they control to the GY.",
       "Continuous", None, None, None, 0, 0, 0, None, None),
    _c(48976825, "Gozen Match", "Trap Card",
       "Each player can only control 1 Attribute of monster. Send all other face-up monsters they control to the GY.",
       "Continuous", None, None, None, 0, 0, 0, None, None),
    _c(24207889, "There Can Be Only One", "Trap Card",
       "Each player can only control 1 monster of each Type. If a player controls 2+ monsters of the same Type, they must send some to the GY so they control no more than 1 of each Type.",
       "Continuous", None, None, None, 0, 0, 0, None, None),
    _c(58616244, "Anti-Spell Fragrance", "Trap Card",
       "Both players must Set Spell Cards before activating them, and cannot activate them until their next turn after Setting them.",
       "Continuous", None, None, None, 0, 0, 0, None, None),
    _c(61740673, "Imperial Order", "Trap Card",
       "Negate all Spell effects on the field. Once per turn, during the Standby Phase, you must pay 700 LP, or destroy this card.",
       "Continuous", None, None, None, 0, 0, 0, None, None, 3),
    _c(5765411, "Vanity's Emptiness", "Trap Card",
       "Neither player can Special Summon monsters. If a card is sent from the Deck or the field to your GY: Destroy this card.",
       "Continuous", None, None, None, 0, 0, 0, None, None, 2),
    _c(30241314, "Macro Cosmos", "Trap Card",
       "When this card resolves: You can Special Summon 1 \"Helios - The Primordial Sun\" from your hand or Deck. While this card is face-up on the field, any card sent to the GY is banished instead.",
       "Continuous", None, None, None, 0, 0, 0, None, None),
    _c(81674782, "Dimensional Fissure", "Spell Card",
       "Any monster sent to the GY is banished instead.",
       "Continuous", None, None, None, 0, 0, 0, None, None),
    _c(823822, "Summon Limit", "Trap Card",
       "Each player can only Summon/Set up to 2 times per turn.",
       "Continuous", None, None, None, 0, 0, 0, None, None),
    _c(68462976, "Secret Village of the Spellcasters", "Spell Card",
       "If you control a Spellcaster monster and your opponent does not, your opponent cannot activate Spell Cards. If you do not control a Spellcaster monster, you cannot activate Spell Cards.",
       "Field", None, None, None, 0, 0, 0, None, None),
    _c(47355498, "Necrovalley", "Spell Card",
       "All \"Gravekeeper's\" monsters gain 500 ATK and DEF. Cards in the GY cannot be banished. Negate any card effect that would move a card in the GY to a different place. Negate any card effect that changes Types or Attributes in the GY.",
       "Field", "Gravekeeper's", None, None, 0, 0, 0, None, None),

    # ===== KAIJUS =====
    _c(55063751, "Gameciel, the Sea Turtle Kaiju", "Effect Monster",
       "You can Special Summon this card (from your hand) to your opponent's field in Attack Position, by Tributing 1 monster they control.",
       "Aqua", "Kaiju", 2200, 3000, 8, 0, 0, None, "WATER"),
    _c(29726552, "Kumongous, the Sticky String Kaiju", "Effect Monster",
       "You can Special Summon this card (from your hand) to your opponent's field in Attack Position, by Tributing 1 monster they control.",
       "Insect", "Kaiju", 2400, 3000, 7, 0, 0, None, "EARTH"),
    _c(36956512, "Gadarla, the Mystery Dust Kaiju", "Effect Monster",
       "You can Special Summon this card (from your hand) to your opponent's field in Attack Position, by Tributing 1 monster they control.",
       "Insect", "Kaiju", 2700, 1600, 8, 0, 0, None, "WIND"),
    _c(59170782, "Dogoran, the Mad Flame Kaiju", "Effect Monster",
       "You can Special Summon this card (from your hand) to your opponent's field in Attack Position, by Tributing 1 monster they control.",
       "Dinosaur", "Kaiju", 3000, 1200, 8, 0, 0, None, "FIRE"),
    _c(28674152, "Interrupted Kaiju Slumber", "Spell Card",
       "Destroy as many monsters on the field as possible, then Special Summon in Attack Position, 2 monsters with different names from your Deck, 1 to each field. You can only activate 1 \"Interrupted Kaiju Slumber\" per turn.",
       "Normal", "Kaiju", None, None, 0, 0, 0, None, None),

    # ===== EXTRA DECK STAPLES - LINK MONSTERS =====
    _c(86066372, "Accesscode Talker", "Link Monster",
       "2+ Effect Monsters - When this card is Link Summoned: You can target 1 Link Monster that was used as material; this card gains ATK equal to that monster's Link Rating x 1000. You can banish 1 Link Monster from your field or GY; destroy 1 card your opponent controls.",
       "Cyberse", None, 2300, None, 0, 0, 4, None, "DARK"),
    _c(26165925, "Knightmare Unicorn", "Link Monster",
       "2+ monsters with different names - If this card is Link Summoned: You can discard 1 card, then target 1 card on the field; shuffle it into the Deck, then, if this card was co-linked when this effect was activated, you can draw 1 card.",
       "Fiend", "Knightmare", 2200, None, 0, 0, 3, None, "DARK"),
    _c(2857636, "Knightmare Phoenix", "Link Monster",
       "2 monsters with different names - If this card is Link Summoned: You can discard 1 card, then target 1 Spell/Trap on the field; destroy it, then, if this card was co-linked, you can draw 1 card.",
       "Fiend", "Knightmare", 1900, None, 0, 0, 2, None, "FIRE"),
    _c(75452921, "Knightmare Cerberus", "Link Monster",
       "2 monsters with different names - If this card is Link Summoned: You can discard 1 card, then target 1 Special Summoned monster in the Main Monster Zone; destroy it, then, if this card was co-linked, you can draw 1 card.",
       "Fiend", "Knightmare", 1600, None, 0, 0, 2, None, "EARTH"),
    _c(10158145, "I:P Masquerena", "Link Monster",
       "2 non-Link Monsters - During your opponent's Main Phase, you can: Immediately after this effect resolves, Link Summon 1 Link Monster using materials you control, including this card. A Link Monster Link Summoned using this card as material cannot be destroyed by your opponent's card effects.",
       "Cyberse", None, 800, None, 0, 0, 2, None, "DARK"),
    _c(29301450, "S:P Little Knight", "Link Monster",
       "2 monsters, including a monster Special Summoned from the Extra Deck - If this card is Link Summoned: You can target 1 card on the field or in either GY; banish it. During either player's turn, if a card or effect is activated: You can banish both this card and 1 monster this card points to until the next Standby Phase.",
       "Warrior", None, 1600, None, 0, 0, 2, None, "LIGHT"),
    _c(64631466, "Apollousa, Bow of the Goddess", "Link Monster",
       "2+ monsters with different names, except Tokens - You can only control 1 \"Apollousa, Bow of the Goddess\". The Original ATK of this card becomes 800 x the number of Link Materials used for its Link Summon. Each time a monster effect is activated (Quick Effect): You can make this card lose exactly 800 ATK; negate that activation.",
       "Fairy", None, 800, None, 0, 0, 4, None, "WIND"),
    _c(98127546, "Underworld Goddess of the Closed World", "Link Monster",
       "4+ Effect Monsters, including 1+ opponent's - Unaffected by activated effects from any monster Special Summoned from the Extra Deck. When this card is Link Summoned: You can negate the effects of all face-up monsters your opponent currently controls.",
       "Fiend", None, 3000, None, 0, 0, 5, None, "DARK"),
    _c(60303688, "Salamangreat Almiraj", "Link Monster",
       "1 Normal Summoned/Set monster with 1000 or less ATK",
       "Cyberse", "Salamangreat", 0, None, 0, 0, 1, None, "FIRE"),
    _c(41999284, "Linkuriboh", "Link Monster",
       "1 Level 1 monster - When an opponent's monster declares an attack: You can Tribute this card; change that opponent's monster's ATK to 0, until the end of this turn.",
       "Cyberse", None, 300, None, 0, 0, 1, None, "DARK"),
    _c(98978921, "Relinquished Anima", "Link Monster",
       "1 Level 1 monster - Once per turn: You can target 1 face-up monster this card points to; equip that target to this card. This card gains ATK equal to that equipped monster's ATK.",
       "Spellcaster", None, 0, None, 0, 0, 1, None, "DARK"),
    _c(98978950, "Link Spider", "Link Monster",
       "1 Normal Monster - Once per turn: You can Special Summon 1 Level 4 or lower Normal Monster from your hand to your zone this card points to.",
       "Cyberse", None, 1000, None, 0, 0, 1, None, "EARTH"),
    _c(3679218, "Linguriboh", "Link Monster",
       "1 Level 1 monster - When your opponent activates a Trap Card or effect that targets a monster(s) you control (Quick Effect): You can Tribute this card; negate the activation, and if you do, destroy that card.",
       "Cyberse", None, 0, None, 0, 0, 1, None, "DARK"),

    # ===== EXTRA DECK STAPLES - XYZ =====
    _c(90448279, "Divine Arsenal AA-ZEUS - Sky Thunder", "XYZ Monster",
       "2 Level 12 monsters - Once per turn, if an Xyz Monster battled this turn, you can also Xyz Summon this card by using 1 Xyz Monster you control as material. (Quick Effect): You can detach 2 materials from this card; send all other cards on the field to the GY.",
       "Machine", None, 3000, 3000, 0, 12, 0, None, "LIGHT"),
    _c(21044178, "Abyss Dweller", "XYZ Monster",
       "2 Level 4 monsters - While this card has material, your opponent cannot activate any card effects in the GY. Once per turn: You can detach 1 material; all WATER monsters you currently control gain 500 ATK until the end of this turn.",
       "Sea Serpent", None, 1700, 1400, 0, 4, 0, None, "WATER"),
    _c(90590303, "Number 41: Bagooska the Terribly Tired Tapir", "XYZ Monster",
       "2 Level 4 monsters - Once per turn, during your Standby Phase: Detach 1 material from this card. If you cannot, destroy this card. While in Defense Position, this card's effects change to: All face-up monsters on the field are changed to Defense Position, also negate the activated effects of monsters that were in Defense Position when that effect was activated.",
       "Fiend", None, 2100, 2000, 0, 4, 0, None, "EARTH"),
    _c(2511, "Tornado Dragon", "XYZ Monster",
       "2 Level 4 monsters - Once per turn (Quick Effect): You can detach 1 material from this card, then target 1 Spell/Trap on the field; destroy it.",
       "Wyrm", None, 2100, 2000, 0, 4, 0, None, "WIND"),
    _c(82633039, "Castel, the Skyblaster Musketeer", "XYZ Monster",
       "2 Level 4 monsters - You can detach 1 material from this card, then target 1 face-up monster on the field; change it to face-down Defense Position. You can detach 2 materials, then target 1 face-up card on the field; shuffle it into the Deck.",
       "Winged Beast", None, 2000, 1500, 0, 4, 0, None, "WIND"),
    _c(95581756, "Number 60: Dugares the Timeless", "XYZ Monster",
       "2 Level 4 monsters - You can detach 2 materials from this card, then activate 1 of these: Draw 2 cards, then discard 1. Special Summon 1 monster from your GY in Defense Position. This turn, 1 monster you control gains ATK equal to its original ATK.",
       "Warrior", None, 1200, 1200, 0, 4, 0, None, "LIGHT"),
    _c(59242457, "Time Thief Redoer", "XYZ Monster",
       "2 Level 4 monsters - Once per turn, during the Standby Phase: You can attach the top card of your opponent's Deck to this card as material. You can detach up to 3 different types of materials from this card; apply the matching effects. Monster: Draw 1 card. Spell: This card can attack directly this turn. Trap: Return 1 face-up card your opponent controls to the hand.",
       "Psychic", "Time Thief", 2400, 2000, 0, 4, 0, None, "DARK"),

    # ===== EXTRA DECK STAPLES - SYNCHRO =====
    _c(84815190, "Baronne de Fleur", "Synchro Monster",
       "1 Tuner + 1+ non-Tuner monsters - Once per turn: You can target 1 card on the field; destroy it. Once per turn, when a card or effect is activated (Quick Effect): You can negate the activation, and if you do, destroy that card. You can only use the previous effect of this card once per turn. Once per turn, during your Standby Phase: You can target 1 Level 9 or lower monster in your GY; return this card to the Extra Deck, and if you do, Special Summon that monster.",
       "Warrior", None, 3000, 2400, 10, 0, 0, None, "WIND"),
    _c(56148713, "Borreload Savage Dragon", "Synchro Monster",
       "1 Tuner + 1+ non-Tuner monsters - If this card is Synchro Summoned: You can equip 1 Link Monster from your GY to this card, and if you do, place Borrel Counters on this card equal to that Link Monster's Link Rating. This card gains ATK equal to half the ATK of the monster equipped to it by its effect. When your opponent activates a card or effect (Quick Effect): You can remove 1 Borrel Counter from this card; negate the activation.",
       "Dragon", "Borrel", 3000, 2500, 8, 0, 0, None, "DARK"),
    _c(41999284, "Crystal Wing Synchro Dragon", "Synchro Monster",
       "1 Tuner + 1+ non-Tuner Synchro Monsters - Once per turn, when another monster's effect is activated (Quick Effect): You can negate the activation, and if you do, destroy that monster, and if you do that, this card gains ATK equal to the destroyed monster's original ATK until the end of this turn. If this card battles a Level 5 or higher monster your opponent controls, during damage calculation: This card gains ATK equal to the current ATK of the opponent's monster it is battling during that damage calculation only.",
       "Dragon", None, 3000, 2500, 8, 0, 0, None, "WIND"),
    _c(74586817, "PSY-Framelord Omega", "Synchro Monster",
       "1 Tuner + 1+ non-Tuner monsters - Once per turn, during your Main Phase: You can banish both this card from the field and 1 random card from your opponent's hand, face-up, until your next Standby Phase. Once per turn, during your opponent's Standby Phase: You can target 1 banished card; return it to the GY.",
       "Psychic", "PSY-Frame", 2800, 2200, 8, 0, 0, None, "LIGHT"),
    _c(79606837, "Herald of Arc Light", "Synchro Monster",
       "1 Tuner + 1+ non-Tuner monsters - Any card sent from the hand or Main Deck to the GY is banished instead. When a Spell/Trap Card, or monster effect, is activated (Quick Effect): You can Tribute this card; negate the activation, and if you do, destroy that card. If this card is sent to the GY: You can add 1 Ritual Monster or 1 Ritual Spell from your Deck to your hand.",
       "Fairy", None, 600, 1000, 4, 0, 0, None, "LIGHT"),
    _c(44508094, "Stardust Dragon", "Synchro Monster",
       "1 Tuner + 1+ non-Tuner monsters - When a card or effect is activated that would destroy a card(s) on the field (Quick Effect): You can Tribute this card; negate the activation, and if you do, destroy it. During the End Phase, if this effect was activated this turn (and was not negated): You can Special Summon this card from your GY.",
       "Dragon", "Stardust", 2500, 2000, 8, 0, 0, None, "WIND"),

    # ===== EXTRA DECK STAPLES - FUSION =====
    _c(80532587, "Elder Entity N'tss", "Fusion Monster",
       "1 Synchro Monster + 1 Xyz Monster - Must be either Fusion Summoned, or Special Summoned by sending the above cards you control to the GY. If this card is Special Summoned: You can destroy 1 card on the field. If this card is sent to the GY: You can target 1 card on the field; destroy it.",
       "Fairy", None, 2500, 1200, 4, 0, 0, None, "EARTH"),
    _c(20326854, "Mudragon of the Swamp", "Fusion Monster",
       "2 monsters with the same Attribute but different Types - Your opponent cannot target monsters on the field with the same Attribute as this card with card effects. Once per turn (Quick Effect): You can declare 1 Attribute; this card becomes that Attribute until the end of this turn.",
       "Dragon", None, 1900, 1600, 4, 0, 0, None, "WATER"),
    _c(41209827, "Starving Venom Fusion Dragon", "Fusion Monster",
       "2 DARK monsters on the field - If this card is Fusion Summoned: You can make this card gain ATK equal to 1 opponent's Special Summoned monster, until the end of this turn. Once per turn: You can target 1 Level 5 or higher monster your opponent controls; until the end of this turn, this card's name becomes that monster's original name, and replace this effect with that monster's original effects.",
       "Dragon", None, 2800, 2000, 8, 0, 0, None, "DARK"),
    _c(16508927, "Predaplant Dragostapelia", "Fusion Monster",
       "1 Fusion Monster + 1 DARK monster - Once per turn (Quick Effect): You can target 1 face-up monster your opponent controls; place 1 Predator Counter on it, and if it is a Level 2 or higher monster, it becomes Level 1 as long as it has a Predator Counter. Negate the activated effects of your opponent's monsters that have Predator Counters.",
       "Plant", "Predaplant", 2700, 1900, 8, 0, 0, None, "DARK"),
    _c(72586085, "Garura, Wings of Resonant Life", "Fusion Monster",
       "2 monsters with the same Type but different Attributes - If this card is sent to the GY: You can draw 1 card.",
       "Dragon", None, 1500, 2400, 6, 0, 0, None, "DARK"),

    # ===== BRANDED / DESPIA CORE =====
    _c(44362883, "Branded Fusion", "Spell Card",
       "Fusion Summon 1 Fusion Monster that lists a \"Fallen of Albaz\" as material from your Extra Deck, using monsters from your hand, field, or Deck as Fusion Material, but you cannot Special Summon monsters from the Extra Deck for the rest of this turn, except Fusion Monsters. You can only activate 1 \"Branded Fusion\" per turn.",
       "Normal", "Branded", None, None, 0, 0, 0, None, None),
    _c(68468459, "Fallen of Albaz", "Effect Monster",
       "If this card is Normal or Special Summoned: You can discard 1 card; Fusion Summon 1 Fusion Monster from your Extra Deck, using monsters on either field as material, including this card. If this card is sent to the GY by a card effect: You can add 1 \"Branded\" Spell/Trap from your Deck to your hand. You can only use each effect of \"Fallen of Albaz\" once per turn.",
       "Dragon", "Branded", 1800, 0, 4, 0, 0, None, "DARK"),
    _c(6637331, "Lubellion the Searing Dragon", "Fusion Monster",
       "\"Fallen of Albaz\" + 1 DARK monster - If this card is Fusion Summoned: You can discard 1 card; Fusion Summon 1 Level 8 or higher Fusion Monster from your Extra Deck, by banishing Fusion Materials listed on it from your hand, field, or GY, but for the rest of this turn, this card cannot attack.",
       "Dragon", "Branded", 2500, 3000, 8, 0, 0, None, "FIRE"),
    _c(26674724, "Albion the Branded Dragon", "Fusion Monster",
       "\"Fallen of Albaz\" + 1 LIGHT monster - If this card is Fusion Summoned: You can Fusion Summon 1 Level 8 or higher Fusion Monster from your Extra Deck. During the End Phase, if this card is in the GY because it was sent there this turn: You can add 1 \"Branded\" Spell/Trap from your Deck to your hand.",
       "Dragon", "Branded", 2500, 2000, 8, 0, 0, None, "DARK"),
    _c(60303245, "Branded in Red", "Trap Card",
       "Fusion Summon 1 Fusion Monster from your Extra Deck that lists \"Fallen of Albaz\" as material, by shuffling Fusion Materials listed on it into the Deck, from among your cards on the field, in your GY, and/or your face-up banished cards, during your opponent's turn.",
       "Quick-Play", "Branded", None, None, 0, 0, 0, None, None),
    _c(25926710, "Branded Lost", "Spell Card",
       "When a \"Branded\" Spell/Trap Card or effect is activated: Neither player can activate cards or effects in response. If a Fusion Monster(s) is Fusion Summoned: You can add 1 \"Fallen of Albaz\" or 1 \"Branded\" Spell/Trap from your Deck to your hand.",
       "Continuous", "Branded", None, None, 0, 0, 0, None, None),
    _c(33431472, "Aluber the Jester of Despia", "Effect Monster",
       "If this card is Normal or Special Summoned: You can add 1 \"Branded\" Spell/Trap from your Deck to your hand. You can only use this effect of \"Aluber the Jester of Despia\" once per turn.",
       "Fairy", "Despia", 1800, 0, 4, 0, 0, None, "DARK"),
    _c(60465049, "Despian Tragedy", "Effect Monster",
       "If this card is sent to the GY by card effect: You can add 1 \"Despia\" monster from your Deck to your hand, or, if \"Branded\" Fusion is in your GY, you can Special Summon 1 \"Despia\" monster from your Deck instead. You can only use this effect of \"Despian Tragedy\" once per turn.",
       "Fairy", "Despia", 1700, 1200, 4, 0, 0, None, "DARK"),
    _c(87327776, "Ad Libitum of Despia", "Effect Monster",
       "If a Fusion Monster(s) is sent to your GY by card effect: You can Special Summon this card from your hand or GY. If this card is Special Summoned: You can target 1 Level 8 or higher Fusion Monster in your GY; Special Summon it.",
       "Fairy", "Despia", 1200, 2500, 8, 0, 0, None, "DARK"),
    _c(41373230, "Mirrorjade the Iceblade Dragon", "Fusion Monster",
       "\"Fallen of Albaz\" + 1 monster that mentions it - Once per turn (Quick Effect): You can banish 1 monster from your Extra Deck that mentions \"Fallen of Albaz\"; banish 1 monster on the field. If this Fusion Summoned card in its owner's control leaves the field because of an opponent's card: You can destroy all monsters your opponent controls, during the End Phase of this turn.",
       "Dragon", "Branded", 3000, 2500, 8, 0, 0, None, "DARK"),
    _c(58986837, "Guardian Chimera", "Fusion Monster",
       "3 monsters with different names - Must be Fusion Summoned using monsters from both your hand and field. If this card is Fusion Summoned: You can draw cards equal to the number of cards used as material from the hand, then destroy cards your opponent controls equal to materials used from the field.",
       "Beast", None, 3300, 3300, 12, 0, 0, None, "LIGHT"),

    # ===== BLUE-EYES CORE =====
    _c(89631139, "Blue-Eyes White Dragon", "Normal Monster",
       "This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.",
       "Dragon", "Blue-Eyes", 3000, 2500, 8, 0, 0, None, "LIGHT"),
    _c(38517737, "Blue-Eyes Alternative White Dragon", "Effect Monster",
       "Cannot be Normal Summoned/Set. Must first be Special Summoned by revealing 1 \"Blue-Eyes White Dragon\" in your hand. You can only Special Summon \"Blue-Eyes Alternative White Dragon\" once per turn this way. This card's name becomes \"Blue-Eyes White Dragon\" while on the field or in the GY. Once per turn: You can target 1 monster your opponent controls; destroy it. This card cannot attack the turn this effect is activated.",
       "Dragon", "Blue-Eyes", 3000, 2500, 8, 0, 0, None, "LIGHT"),
    _c(71039903, "Sage with Eyes of Blue", "Tuner Monster",
       "When this card is Normal Summoned: You can add 1 Level 1 LIGHT Tuner from your Deck to your hand. You can send this card from your hand to the GY, then target 1 Effect Monster you control; send it to the GY, and if you do, Special Summon 1 \"Blue-Eyes White Dragon\" from your Deck.",
       "Spellcaster", "Blue-Eyes", 0, 1500, 1, 0, 0, None, "LIGHT"),
    _c(73398797, "White Stone of Ancients", "Tuner Monster",
       "During the End Phase, if this card is in the GY because it was sent there this turn: You can Special Summon 1 \"Blue-Eyes\" monster from your Deck. You can banish this card from your GY, then target 1 \"Blue-Eyes\" monster in your GY; add it to your hand.",
       "Dragon", "Blue-Eyes", 600, 500, 1, 0, 0, None, "LIGHT"),
    _c(9742784, "The White Stone of Legend", "Tuner Monster",
       "If this card is sent to the GY: Add 1 \"Blue-Eyes White Dragon\" from your Deck to your hand.",
       "Dragon", "Blue-Eyes", 300, 250, 1, 0, 0, None, "LIGHT"),
    _c(43228023, "Blue-Eyes Spirit Dragon", "Synchro Monster",
       "1 Tuner + 1+ non-Tuner \"Blue-Eyes\" monsters - Neither player can Special Summon 2 or more monsters at the same time. Once per turn (Quick Effect): You can negate the activation of an effect of a card in the GY. During either player's turn: You can Tribute this Synchro Summoned card; Special Summon 1 LIGHT Dragon Synchro Monster from your Extra Deck in Defense Position, except \"Blue-Eyes Spirit Dragon\", but destroy it during the End Phase.",
       "Dragon", "Blue-Eyes", 2500, 3000, 9, 0, 0, None, "LIGHT"),
    _c(95832338, "Blue-Eyes Twin Burst Dragon", "Fusion Monster",
       "\"Blue-Eyes White Dragon\" + \"Blue-Eyes White Dragon\" - Must be either Fusion Summoned, or Special Summoned by sending the above cards you control to the GY. Cannot be destroyed by battle. If this card battles an opponent's monster, after damage calculation: Banish that monster.",
       "Dragon", "Blue-Eyes", 3000, 2500, 10, 0, 0, None, "LIGHT"),
    _c(20654247, "Melody of Awakening Dragon", "Spell Card",
       "Discard 1 card; add up to 2 Dragon monsters with 3000 or more ATK and 2500 or less DEF from your Deck to your hand.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(97268402, "Trade-In", "Spell Card",
       "Discard 1 Level 8 monster; draw 2 cards.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(24094258, "Return of the Dragon Lords", "Spell Card",
       "Target 1 Level 7 or 8 Dragon monster in your GY; Special Summon it. If a Dragon monster(s) you control would be destroyed by battle or card effect, you can banish this card from your GY instead.",
       "Normal", None, None, None, 0, 0, 0, None, None),
    _c(43521585, "The Melody of Awakening Dragon", "Spell Card",
       "Discard 1 card; add up to 2 Dragon monsters with 3000+ ATK and 2500 or less DEF from your Deck to your hand.",
       "Normal", None, None, None, 0, 0, 0, None, None),

    # ===== SKY STRIKER CORE =====
    _c(26077387, "Sky Striker Ace - Raye", "Effect Monster",
       "If this card is in your GY (Quick Effect): You can Tribute 1 monster you control; Special Summon this card. You can only use this effect of \"Sky Striker Ace - Raye\" once per turn. If this card on the field is sent to the GY or banished: You can Special Summon 1 \"Sky Striker Ace\" monster from your Extra Deck to the Extra Monster Zone.",
       "Warrior", "Sky Striker", 1500, 1500, 4, 0, 0, None, "DARK"),
    _c(25955749, "Sky Striker Ace - Roze", "Effect Monster",
       "If your opponent Special Summons a monster(s) to the Extra Monster Zone: You can Special Summon this card from your hand. If a face-up \"Sky Striker\" Link Monster you control is destroyed by battle or card effect: You can Special Summon this card from your GY.",
       "Warrior", "Sky Striker", 1500, 1500, 4, 0, 0, None, "LIGHT"),
    _c(63288573, "Sky Striker Ace - Shizuku", "Link Monster",
       "1 non-Token \"Sky Striker\" monster - If this card is Special Summoned: You can target 1 card your opponent controls; that card cannot activate its effects this turn. Once per turn, during the End Phase: You can add 1 \"Sky Striker\" Spell from your Deck to your hand with a different name from every card in your GY.",
       "Machine", "Sky Striker", 1500, None, 0, 0, 1, None, "WATER"),
    _c(26355365, "Sky Striker Ace - Kagari", "Link Monster",
       "1 non-Token \"Sky Striker\" monster - If this card is Special Summoned: You can target 1 \"Sky Striker\" Spell in your GY; add it to your hand.",
       "Machine", "Sky Striker", 1500, None, 0, 0, 1, None, "FIRE"),
    _c(8491308, "Sky Striker Ace - Hayate", "Link Monster",
       "1 non-Token \"Sky Striker\" monster - This card can attack directly. After damage calculation, if this card battled: You can send 1 \"Sky Striker\" card from your Deck to the GY.",
       "Machine", "Sky Striker", 1500, None, 0, 0, 1, None, "WIND"),
    _c(24010609, "Sky Striker Mobilize - Engage!", "Spell Card",
       "Add 1 \"Sky Striker\" card from your Deck to your hand, except \"Sky Striker Mobilize - Engage!\". If you have 3 or more Spells in your GY: You can also draw 1 card.",
       "Normal", "Sky Striker", None, None, 0, 0, 0, None, None),
    _c(63166095, "Sky Striker Mecha - Widow Anchor", "Spell Card",
       "If you control no monsters in your Main Monster Zones: Target 1 Effect Monster on the field; negate its effects until the end of this turn. If you have 3 or more Spells in your GY, you can also take control of that monster until the End Phase.",
       "Quick-Play", "Sky Striker", None, None, 0, 0, 0, None, None),
    _c(52340444, "Sky Striker Mecha - Shark Cannon", "Spell Card",
       "If you control no monsters in your Main Monster Zones: Target 1 monster in your opponent's GY; banish it, or if you have 3 or more Spells in your GY, you can Special Summon that monster to your field instead, but it cannot attack.",
       "Quick-Play", "Sky Striker", None, None, 0, 0, 0, None, None),
    _c(98338152, "Sky Striker Mecha Modules - Multirole", "Spell Card",
       "Once per turn: You can target 1 other card you control; send it to the GY. Your opponent cannot activate cards or effects in response to your \"Sky Striker\" Spell/Trap activations or effects. Once per turn, during the End Phase: You can Set \"Sky Striker\" Spells with different names directly from your GY to your Spell & Trap Zone, up to the number of \"Sky Striker\" Spells activated this turn while this card was face-up.",
       "Continuous", "Sky Striker", None, None, 0, 0, 0, None, None),

    # ===== SNAKE-EYE / FIRE KING CORE =====
    _c(89012457, "Snake-Eye Ash", "Effect Monster",
       "If this card is Normal or Special Summoned: You can add 1 Level 1 FIRE monster from your Deck to your hand. You can send 1 face-up card you control to the GY, then target 1 \"Snake-Eye\" monster in your GY, except \"Snake-Eye Ash\"; Special Summon it. You can only use each effect of \"Snake-Eye Ash\" once per turn.",
       "Pyro", "Snake-Eye", 800, 1000, 1, 0, 0, None, "FIRE"),
    _c(71607202, "Snake-Eyes Poplar", "Effect Monster",
       "If this card is Normal or Special Summoned: You can Special Summon 1 Level 1 FIRE monster from your hand or GY, except \"Snake-Eyes Poplar\". If another monster is placed in your Spell & Trap Zone: You can add 1 \"Snake-Eye\" Spell/Trap from your Deck to your hand. You can only use each effect of \"Snake-Eyes Poplar\" once per turn.",
       "Pyro", "Snake-Eye", 800, 1000, 1, 0, 0, None, "FIRE"),
    _c(64335804, "Snake-Eye Oak", "Effect Monster",
       "You can send 1 face-up card you control to the GY; Special Summon this card from your hand. If this card is sent to the GY by card effect: You can add 1 \"Snake-Eye\" monster from your Deck to your hand, except \"Snake-Eye Oak\". You can only use each effect of \"Snake-Eye Oak\" once per turn.",
       "Pyro", "Snake-Eye", 800, 1000, 1, 0, 0, None, "FIRE"),
    _c(2970, "Original Sinful Spoils - Snake-Eye", "Spell Card",
       "Target 1 card you control and 1 \"Snake-Eye\" monster in your Deck; place the targeted card on the bottom of the Deck, and if you do, Special Summon the monster from your Deck. You can only activate 1 \"Original Sinful Spoils - Snake-Eye\" per turn.",
       "Normal", "Snake-Eye", None, None, 0, 0, 0, None, None),
    _c(3223, "Diabellstar the Black Witch", "Effect Monster",
       "If you control a monster: You can Special Summon this card from your hand, then place 1 card from your hand on the bottom of the Deck. If this card is Normal or Special Summoned: You can Set 1 \"Sinful Spoils\" Spell/Trap directly from your Deck. You can only use each effect of \"Diabellstar the Black Witch\" once per turn.",
       "Spellcaster", None, 2500, 2000, 7, 0, 0, None, "DARK"),

    # ===== SALAMANGREAT CORE =====
    _c(5765212, "Salamangreat Gazelle", "Effect Monster",
       "If a \"Salamangreat\" monster is sent to your GY, except \"Salamangreat Gazelle\" (except during the Damage Step): You can Special Summon this card from your hand. If this card is Normal or Special Summoned: You can send 1 \"Salamangreat\" card from your Deck to the GY. You can only use each effect once per turn.",
       "Cyberse", "Salamangreat", 1500, 1000, 3, 0, 0, None, "FIRE"),
    _c(27748077, "Salamangreat Spinny", "Effect Monster",
       "If you control a \"Salamangreat\" monster: You can Special Summon this card from your GY, but banish it when it leaves the field. You can only use this effect once per turn. If this card is sent to the GY as Link Material: The Link Monster that used this card gains 500 ATK.",
       "Cyberse", "Salamangreat", 1000, 1500, 3, 0, 0, None, "FIRE"),
    _c(82894988, "Salamangreat Foxy", "Effect Monster",
       "If this card is Normal Summoned: You can look at the top 3 cards of your Deck, and if you find a \"Salamangreat\" card, add it to your hand, otherwise place them on top in any order. If a \"Salamangreat\" card is activated (except during the Damage Step): You can Special Summon this card from your GY in Defense Position.",
       "Cyberse", "Salamangreat", 1000, 1200, 3, 0, 0, None, "FIRE"),
    _c(2451, "Salamangreat Sunlight Wolf", "Link Monster",
       "2 FIRE Effect Monsters - If this card is Link Summoned: You can add 1 FIRE monster from your GY to your hand. If this card was Link Summoned using \"Salamangreat Sunlight Wolf\" as material: You can add 1 \"Salamangreat\" Spell/Trap from your GY to your hand. You can only use each effect once per turn.",
       "Cyberse", "Salamangreat", 1800, None, 0, 0, 2, None, "FIRE"),
    _c(60303246, "Salamangreat Balelynx", "Link Monster",
       "1 Level 4 or lower Cyberse monster - If this card is Link Summoned: You can add 1 \"Salamangreat Sanctuary\" from your Deck to your hand. If a \"Salamangreat\" card(s) you control would be destroyed by card effect, you can banish this card from your GY instead.",
       "Cyberse", "Salamangreat", 500, None, 0, 0, 1, None, "FIRE"),
    _c(7601, "Salamangreat Sanctuary", "Spell Card",
       "You can Ritual Summon \"Salamangreat\" Ritual Monsters with this card using monsters from your hand or field as Tributes. Once per turn: You can Link Summon 1 \"Salamangreat\" Link Monster from your Extra Deck by using 1 \"Salamangreat\" Link Monster you control with its same name as material.",
       "Field", "Salamangreat", None, None, 0, 0, 0, None, None),
    _c(68468458, "Salamangreat Circle", "Spell Card",
       "Add 1 \"Salamangreat\" monster from your Deck to your hand.",
       "Quick-Play", "Salamangreat", None, None, 0, 0, 0, None, None),

    # ===== SWORDSOUL / TENYI CORE =====
    _c(93490856, "Swordsoul of Mo Ye", "Effect Monster",
       "If this card is in your hand: You can reveal 1 other \"Swordsoul\" card or 1 \"Tenyi\" monster in your hand; Special Summon this card, then discard the revealed card. If this card is Normal or Special Summoned: You can activate this effect; Special Summon 1 \"Swordsoul Token\", also you cannot Special Summon monsters from the Extra Deck for the rest of this turn, except Synchro Monsters.",
       "Wyrm", "Swordsoul", 1700, 1600, 4, 0, 0, None, "WATER"),
    _c(3223810, "Swordsoul of Taia", "Effect Monster",
       "If this card is Normal or Special Summoned: You can send 1 \"Swordsoul\" card or 1 \"Tenyi\" card from your Deck to the GY. You can banish this card from your GY, then target 1 \"Swordsoul\" card or 1 Wyrm monster in your GY, except this card; add it to your hand.",
       "Wyrm", "Swordsoul", 1600, 1000, 4, 0, 0, None, "WATER"),
    _c(40398568, "Swordsoul Emergence", "Spell Card",
       "Add 1 \"Swordsoul\" monster from your Deck or GY to your hand, except a Tuner. You can only activate 1 \"Swordsoul Emergence\" per turn.",
       "Normal", "Swordsoul", None, None, 0, 0, 0, None, None),
    _c(49829980, "Swordsoul Strategist Longyuan", "Tuner Monster",
       "If a \"Swordsoul\" monster(s) or Wyrm monster(s) is Special Summoned to your field (except during the Damage Step): You can Special Summon this card from your hand, then inflict 1200 damage to your opponent. You can only use this effect once per turn.",
       "Wyrm", "Swordsoul", 1200, 2400, 4, 0, 0, None, "DARK"),
    _c(87052196, "Swordsoul Grandmaster - Chixiao", "Synchro Monster",
       "1 Tuner + 1+ non-Tuner monsters - If this card is Synchro Summoned: You can add 1 \"Swordsoul\" card from your Deck to your hand, except \"Swordsoul Grandmaster - Chixiao\". Once per turn, when a card or effect is activated (Quick Effect): You can banish 1 card from your GY; negate the activation.",
       "Wyrm", "Swordsoul", 2800, 1000, 8, 0, 0, None, "WATER"),
    _c(41373228, "Swordsoul Sinister Sovereign - Qixing Longyuan", "Synchro Monster",
       "1 Tuner + 1+ non-Tuner monsters - Must be Synchro Summoned. When this card is Synchro Summoned: You can banish all cards in the GYs, and if you do, this card gains 100 ATK/DEF for each card banished.",
       "Wyrm", "Swordsoul", 3000, 3000, 10, 0, 0, None, "WATER"),

    # ===== LABRYNTH CORE =====
    _c(61901281, "Lady Labrynth of the Silver Castle", "Effect Monster",
       "If a Normal Trap Card is activated: You can Special Summon this card from your hand. Once per turn, if a card(s) leaves your opponent's field by a card effect: You can target 1 of those cards; Set it to your field. You can only use the first effect of this card once per turn.",
       "Fiend", "Labrynth", 3000, 2900, 8, 0, 0, None, "DARK"),
    _c(33985573, "Lovely Labrynth of the Silver Castle", "Effect Monster",
       "If a Normal Trap Card is activated: You can Special Summon this card from your hand. If a card(s) is sent from the field to your opponent's GY by a card effect: You can banish 1 of them. You can only use each effect once per turn.",
       "Fiend", "Labrynth", 2900, 1900, 8, 0, 0, None, "DARK"),
    _c(87459919, "Arianna the Labrynth Servant", "Effect Monster",
       "When this card is Normal Summoned: You can add 1 \"Labrynth\" Spell/Trap from your Deck to your hand. If a Normal Trap Card is activated: You can Special Summon 1 Fiend monster from your hand with a different name than the monsters you control.",
       "Fiend", "Labrynth", 1600, 2400, 4, 0, 0, None, "DARK"),
    _c(33854624, "Arias the Labrynth Butler", "Effect Monster",
       "If you activate a Normal Trap Card (except during the Damage Step): You can Special Summon this card from your hand, and if you do, you can Set 1 Normal Trap from your GY that you have not activated this turn. You can only use this effect once per turn.",
       "Fiend", "Labrynth", 1800, 1000, 4, 0, 0, None, "DARK"),
    _c(76587747, "Welcome Labrynth", "Trap Card",
       "Special Summon 1 \"Labrynth\" monster from your hand or Deck. If you control a Level 8 or higher Fiend monster, you can also apply 1 of these effects. Return 1 monster your opponent controls to the hand. Send 1 Spell/Trap your opponent controls to the GY.",
       "Normal", "Labrynth", None, None, 0, 0, 0, None, None),
    _c(76821236, "Big Welcome Labrynth", "Trap Card",
       "Special Summon 1 Fiend monster from your hand or Deck. If you control a Level 8 or higher Fiend monster, you can also banish 1 card your opponent controls.",
       "Normal", "Labrynth", None, None, 0, 0, 0, None, None),
    _c(46325429, "Labrynth Labyrinth", "Spell Card",
       "Each time a Normal Trap Card is activated, gain 500 LP. If you activate a Normal Trap Card (except during the Damage Step): You can Set 1 \"Labrynth\" Spell/Trap directly from your Deck, except \"Labrynth Labyrinth\". You can only use this effect once per turn.",
       "Field", "Labrynth", None, None, 0, 0, 0, None, None),

    # ===== MISC USEFUL MONSTERS =====
    _c(65192027, "Fantastical Dragon Phantazmay", "Effect Monster",
       "If your opponent Special Summons a Link Monster(s): You can Special Summon this card from your hand, and if you do, draw cards equal to the number of Link Monsters your opponent controls +1, then shuffle cards from your hand into the Deck equal to the number of Link Monsters your opponent controls.",
       "Dragon", None, 2400, 1800, 7, 0, 0, None, "DARK"),
    _c(44095762, "Lava Golem", "Effect Monster",
       "Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) to your opponent's side of the field by Tributing 2 monsters they control. You cannot Normal Summon/Set the turn you Special Summon this card. During each of your Standby Phases: The controller of this card takes 1000 damage.",
       "Fiend", None, 3000, 2500, 8, 0, 0, None, "FIRE"),
    _c(10000080, "The Winged Dragon of Ra - Sphere Mode", "Effect Monster",
       "Cannot be Special Summoned. Requires 3 Tributes from either side of the field to Normal Summon to that side of the field. Cannot attack. Your opponent cannot target this card for attacks or card effects.",
       "Divine-Beast", None, 0, 0, 10, 0, 0, None, "DIVINE"),
    _c(76812113, "Inspector Boarder", "Effect Monster",
       "Cannot be Special Summoned. Each player can only activate 1 monster effect per turn for each type of monster card they control (Ritual, Fusion, Synchro, Xyz, Pendulum, Link).",
       "Fiend", None, 2000, 2000, 4, 0, 0, None, "LIGHT"),
    _c(24140059, "Amano-Iwato", "Spirit Monster",
       "Cannot be Special Summoned. During the turn this card was Normal Summoned, your opponent cannot activate monster effects, except for monsters that were already face-up when this card was Normal Summoned. Once per turn, during the End Phase: Return this card to the hand.",
       "Rock", None, 1900, 1200, 4, 0, 0, None, "EARTH"),
    _c(31764700, "Denko Sekka", "Effect Monster",
       "Cannot be Special Summoned. While you control no Set Spell/Trap Cards, neither player can Set Spell/Trap Cards nor activate Spell/Trap Cards that are Set on the field.",
       "Thunder", None, 1700, 1000, 4, 0, 0, None, "LIGHT"),
    _c(75878039, "Majesty's Fiend", "Effect Monster",
       "Cannot be Special Summoned. Neither player can activate monster effects.",
       "Fiend", None, 2400, 1000, 6, 0, 0, None, "LIGHT"),
    _c(10802915, "Vanity's Fiend", "Effect Monster",
       "Cannot be Special Summoned. Neither player can Special Summon monsters.",
       "Fiend", None, 2400, 1200, 6, 0, 0, None, "DARK"),
    _c(20155904, "Jizukiru, the Star Destroying Kaiju", "Effect Monster",
       "You can Special Summon this card (from your hand) to your opponent's field in Attack Position, by Tributing 1 monster they control.",
       "Machine", "Kaiju", 3300, 2600, 10, 0, 0, None, "LIGHT"),
    _c(41268525, "Radian, the Multidimensional Kaiju", "Effect Monster",
       "You can Special Summon this card (from your hand) to your opponent's field in Attack Position, by Tributing 1 monster they control.",
       "Fiend", "Kaiju", 2800, 2500, 7, 0, 0, None, "DARK"),
    _c(90432163, "Thunder King, the Lightningstrike Kaiju", "Effect Monster",
       "You can Special Summon this card (from your hand) to your opponent's field in Attack Position, by Tributing 1 monster they control.",
       "Thunder", "Kaiju", 3300, 2100, 9, 0, 0, None, "LIGHT"),

    # ===== MISC SPELLS/TRAPS FOR DECK COMPLETENESS =====
    _c(70368879, "Instant Fusion", "Spell Card",
       "Pay 1000 LP; Special Summon 1 Level 5 or lower Fusion Monster from your Extra Deck, but it cannot attack, also it is destroyed during the End Phase. (This is treated as a Fusion Summon.)",
       "Normal", None, None, None, 0, 0, 0, None, None, 2),
    _c(55144522, "Pot of Greed", "Spell Card",
       "Draw 2 cards.",
       "Normal", None, None, None, 0, 0, 0, None, None, 3),
    _c(67616300, "Graceful Charity", "Spell Card",
       "Draw 3 cards, then discard 2 cards.",
       "Normal", None, None, None, 0, 0, 0, None, None, 3),
    _c(72892473, "Delinquent Duo", "Spell Card",
       "Pay 1000 LP; your opponent randomly discards 1 card, then your opponent discards 1 more card.",
       "Normal", None, None, None, 0, 0, 0, None, None, 3),
    _c(57953380, "Snatch Steal", "Spell Card",
       "Equip only to a monster your opponent controls. Take control of the equipped monster. During each of your opponent's Standby Phases: The controller of the equipped monster gains 1000 LP.",
       "Equip", None, None, None, 0, 0, 0, None, None, 3),
]
# fmt: on


def get_bundled_cards() -> list[dict]:
    """Return the bundled card data in API-compatible format."""
    return BUNDLED_CARDS
